"""add created_by to rooms and weapons

Revision ID: 5cdd290f4c56
Revises: 6112f5e99c5c
Create Date: 2026-03-01 22:02:02.398490

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5cdd290f4c56"
down_revision: Union[str, None] = "6112f5e99c5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_by", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            "fk_rooms_created_by_players", "players", ["created_by"], ["id"]
        )

    with op.batch_alter_table("weapons", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_by", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            "fk_weapons_created_by_players", "players", ["created_by"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("weapons", schema=None) as batch_op:
        batch_op.drop_constraint("fk_weapons_created_by_players", type_="foreignkey")
        batch_op.drop_column("created_by")

    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.drop_constraint("fk_rooms_created_by_players", type_="foreignkey")
        batch_op.drop_column("created_by")

    # ### end Alembic commands ###
