"""initial schema

Revision ID: 6112f5e99c5c
Revises:
Create Date: 2026-02-28 16:28:06.470275

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6112f5e99c5c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "lobby", "in_progress", "finished", name="gamestatus", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("host_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["host_id"], ["players.id"], name="fk_game_host_id", use_alter=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.create_index("ix_games_code", ["code"], unique=True)

    op.create_table(
        "players",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("is_alive", sa.Boolean(), nullable=False),
        sa.Column("kills", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.create_index("ix_players_game_id", ["game_id"], unique=False)
        batch_op.create_index("ix_players_token", ["token"], unique=True)

    op.create_table(
        "rooms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.create_index("ix_rooms_game_id", ["game_id"], unique=False)

    op.create_table(
        "weapons",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("weapons", schema=None) as batch_op:
        batch_op.create_index("ix_weapons_game_id", ["game_id"], unique=False)

    op.create_table(
        "assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("killer_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("weapon_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["killer_id"], ["players.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["players.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["weapon_id"], ["weapons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("assignments", schema=None) as batch_op:
        batch_op.create_index("ix_assignments_game_active", ["game_id", "is_active"], unique=False)
        batch_op.create_index(
            "ix_assignments_killer_active", ["killer_id", "is_active"], unique=False
        )
        batch_op.create_index(
            "ix_assignments_target_active", ["target_id", "is_active"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assignments", schema=None) as batch_op:
        batch_op.drop_index("ix_assignments_target_active")
        batch_op.drop_index("ix_assignments_killer_active")
        batch_op.drop_index("ix_assignments_game_active")

    op.drop_table("assignments")
    with op.batch_alter_table("weapons", schema=None) as batch_op:
        batch_op.drop_index("ix_weapons_game_id")

    op.drop_table("weapons")
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.drop_index("ix_rooms_game_id")

    op.drop_table("rooms")
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.drop_index("ix_players_token")
        batch_op.drop_index("ix_players_game_id")

    op.drop_table("players")
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.drop_index("ix_games_code")

    op.drop_table("games")
    # ### end Alembic commands ###
