"""add users table and player user_id

Revision ID: e083b6b091da
Revises: 5cdd290f4c56
Create Date: 2026-03-01 22:26:23.075028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e083b6b091da"
down_revision: Union[str, None] = "5cdd290f4c56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=30), nullable=False),
        sa.Column("username_lower", sa.String(length=30), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("ix_users_username_lower", ["username_lower"], unique=True)

    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Uuid(), nullable=True))
        batch_op.create_index("ix_players_user_id", ["user_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_players_user_id_users", "users", ["user_id"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.drop_constraint("fk_players_user_id_users", type_="foreignkey")
        batch_op.drop_index("ix_players_user_id")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("ix_users_username_lower")

    op.drop_table("users")
    # ### end Alembic commands ###
